# Generated by Django 4.1.2 on 2022-12-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0002_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenders",
            fields=[
                ("tenderid", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("subcatname", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("ldate", models.CharField(max_length=10)),
                ("edate", models.CharField(max_length=10)),
                ("info", models.CharField(max_length=50)),
            ],
        ),
    ]
